# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('from_date', models.DateField(verbose_name='Date')),
                ('to_date', models.DateField(verbose_name='Date')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-to_date'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='listed_description',
            field=models.ManyToManyField(blank=True, to='workex.ExperienceDesc'),
        ),
    ]
