# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workex', '0005_auto_20171231_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='listed_description',
        ),
        migrations.AddField(
            model_name='experience',
            name='listed_description',
            field=models.ManyToManyField(blank=True, default='', to='workex.ExperienceDesc'),
        ),
    ]
